[package]
name = "yt-video-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { features = ["derive"], version = "4.5.50" }
dotenv = "0.15.0"
regex = "1.10.5"
tokio = { version = "1.48.0", features = ["full"] }
yt-dlp = "1.3.4"
